### ISSUE TITLE
Add tests and documentations for Milestone 3

### ISSUE THREAD

**Issue by zouwenjiao** [UBC-MDS/altairexpress#38]
- [ ] Add adequate integration tests

- [ ] Add additional test cases, if required

- [x] examine docstrings of your functions

- [ ] examine whether one-line descriptions of your unit test functions make sense
