### ISSUE TITLE
Feedback to Milestone 3

### ISSUE THREAD

**Issue by Doooooris** [UBC-MDS/altairexpress#78]
PYTHON
 - [ ] 1. "from gapminder import gapminder": arise error "No module named 'gapminder'". I have already use the peotry install to install all the dependency list, please check if the 'gapminder' in lock file is correctly documented. (You can test in your local computer: First, pip uninstall gapreminder. Then, poetry install. It doesn't reinstall gapminder)
- [x] 2. "altairexpress.hist(gapminder, gdpPerCap)": What is gdpPerCap?
- [x] 3. In Usage of fourier_transform, add this line "import pandas as pd", since you are using pd.Dataframe in the example input.
- [x] 4. Usage: altairexpress.fourier_transform.fourier_transfor(data = my_data,time_col = 'time_series', data_col = 'signal'). TYPO: fourier_transform not fourier_transfor.
- [x] 5. Usage: If the import is "from altairexpress.fourier_transform import fourier_transform", use fourier_transform() for function call is good enough.
- [x] 6. When I try "from altairexpress import ts" , two error shows up: First one: ModuleNotFoundError: No module named 'pandas.tseries.tools'. Second, cannot import name 'datetools'. Please take a look why this happen.
- [x] 7. Usage: altairexpress.hist(gapminder, gdpPerCap) is not working. Change it to "altairexpress.hist.hist(gapminder, "gdpPercap")" or "hist(gapminder, "gdpPercap")". You have the correct code in DEMO, please be more careful!
- [x] 8. Usage: "from altairexpress.scatter import scatter" is not correct. Please note: the "altairexpress" means the altairexpress folder. The second "scatter" means the python file named "scatter". The last name after "import" should be the NAME OF FUNCTION inside this python file. Change it to: from altairexpress.scatter import make_scatter.
- [x] 9. IMPORTANT!!! Please run and test the USAGE code line by line from the terminal before you submit. (Remember to uninstall all dependency first to pretend you are a brand new user)
- [x] 10. pip install python package failed. Try 'pip install -i https://test.pypi.org/simple/ altairexpress'. Looking in indexes: https://test.pypi.org/simple/
ERROR: Could not find a version that satisfies the requirement altairexpress (from versions: none) ERROR: No matching distribution found for altairexpress.

R
- [x] 11. Example: "gghist(data = iris, variable = Sepal.Length)", What is iris and Sepal? In the example, you need to show the input too. You can either give a screenshot of your input data or give a link to your input data.

**Comment by tejasph** [comment]
Addressed 8 in my latest pull request

**Comment by tejasph** [comment]
Hi Doris, 

For comment number 1, I tried the troubleshooting steps you laid out for us. I uninstalled gap minder and then ran poetry install. On my local computer, the package was still installed successfully with gapminder. I'm not sure why your local computer was having issues. I am using a Mac; maybe that's why?

**Comment by tejasph** [comment]
Hi Doris, 

For comment 10, we tried to find a fix for the errors you were seeing. When I ran the line, I got the following:

```
ERROR: Could not find a version that satisfies the requirement datetools<2.0,>=1.1 (from altairexpress) (from versions: none)
ERROR: No matching distribution found for datetools<2.0,>=1.1 (from altairexpress)

```

According to [someone](https://stackoverflow.com/questions/57151603/how-to-get-pypi-to-automatically-install-dependencies) on Slack, we can't account for these errors unless we have a `setup.py` or a `requirements.txt` file . Instead, the user must upgrade the packages that are being referred to in the error. I'm not sure how to approach fixing this...any advice would be welcome!

**Comment by tejasph** [comment]
Turns out the pip install should be `pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple encoderpy` (thanks to Tom).

Using this commands installs the package without error for me. I also fixed up the usage examples so that they run without error.

**Comment by zouwenjiao** [comment]
After we update the dependencies of our package, when I tried `from altairexpress import ts`, there is no error.
![image](https://user-images.githubusercontent.com/45547666/77692914-b3ab9280-6f64-11ea-8a05-61b0bc9a7aea.png)
This is the latest release that has addressed the problems above:
[v 1.1.24](https://github.com/UBC-MDS/altairexpress/tree/1.1.24)

**Comment by zouwenjiao** [comment]
For the point 11, we added an link of the iris dataset.

You can see the updates [here](https://github.com/UBC-MDS/ggexpress/tree/v1.2.0)
